-- Vector embeddings for tools, powering semantic `search_tools` in search mode.
--
-- Embeddings are generated by the proxy (Gemini) from each tool's name+description and
-- stored here; `search_tools` embeds the query and finds nearest tools by cosine
-- distance. NULL embedding = not yet embedded (or description changed) — the proxy
-- backfills these and falls back to lexical search when embeddings are unavailable.
--
-- Dimension 768 matches EMBEDDING_DIMENSIONS (gemini-embedding-001 truncated via MRL).
-- Changing the dimension requires a new migration.
CREATE EXTENSION IF NOT EXISTS vector;

ALTER TABLE tools ADD COLUMN embedding vector(768);
